# Generated by Django 3.2.14 on 2022-07-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('technician', 'Technician'), ('customer', 'Customer')], default='customer', max_length=13),
        ),
    ]
