# Generated by Django 3.2.14 on 2022-07-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
