# Generated by Django 3.2.14 on 2022-07-23 20:59

from django.db import migrations, models
import tickets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_image',
            field=models.ImageField(blank=True, help_text="Only 'jpg' or 'png' files permitted. Maximum file size is 3MB.", upload_to='', validators=[tickets.validators.validate_image]),
        ),
    ]
