# Generated by Django 3.2.14 on 2022-07-24 18:49

import cloudinary.models
from django.db import migrations
import tickets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Only 'jpg' or 'png' files permitted. Maximum file size is 3MB.", max_length=255, validators=[tickets.validators.validate_image], verbose_name='image'),
        ),
    ]
