# Generated by Django 3.2.14 on 2022-07-30 09:24

import django.core.validators
from django.db import migrations, models
import tickets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20220728_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(validators=[tickets.validators.textfield_not_empty()]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(validators=[tickets.validators.textfield_not_empty(min_length=20)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
